### ISSUE TITLE
Font awesome

### ISSUE THREAD

**Issue by ghost** [patrickmarabeas/jQuery-FontSpy.js#1]
This does not appear to be working for font awesome. 

This may have something to do  with the font-awesome CSS file can already be loaded, but not yet the font itself?

Actually, as soon as this line is executed: 

```
tester.style.fontFamily = config.font + ',' + config.testFont;
```

The offsetWidth already changes (when font awesome is true). So on the first try of checkFont() that already thinks it's finished loading when in fact it isn't.

Can you confirm these findings?

**Comment by spetryjohnson** [comment]
I stumbled across this while trying to find a way to tell if FontAwesome fonts had been loaded or not. 

In my case, I think some of my customers are on a network where ALL web fonts are blocked. So, the solution I used was to use fontSpy to test a "normal" text font, instead of explicitly testing for FA, and then to make the assumption that if the test font failed, FA would fail too.

Just adding it here to help the next poor soul that goes down this same rabbit hole...
